# Generated by Django 5.1.6 on 2025-02-22 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ligtas_ani', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
